feat(providers): add ability to register tax and fulfillment providers using medusa-extender annotations
adrien2p/medusa-extender pull request #146
Opened 2022-11-21 22:53 UTC by dwene

2022-11-22 06:01 UTC, dwene commented
@adrien2p ok I added some unit and integration tests! I'd like to start with these 2 fulfillment providers for now, but I'm setting up patterns here to be used again for payment, search, notification, file, oauth,  and other future providers!

2022-11-22 06:03 UTC, dwene commented
Also this closes #128

2022-11-22 08:41 UTC, adrien2p requested changes
Looks very nice, Can I get you to resolve the codeQL comment as well and mine and it should be ready to merge 🚀

2022-11-22 08:41 UTC, adrien2p commented on src/decorators/providers.decorator.ts
> + * Mark a class as an entity to be used by the loader.
todo: update

2022-11-22 08:41 UTC, adrien2p commented on src/loaders/plugins.loader.ts
> +import { container } from 'webpack';
todo: rm

2022-11-22 22:28 UTC, adrien2p approved these changes
LGTM 🔥

2022-11-22 23:09 UTC, dwene commented
Sweet! Let's ship it!

2022-11-23 07:46 UTC, merged

2022-11-23 07:47 UTC, adrien2p commented
@dwene i ve merged it. Can I get you to update the doc please?