feat: updated to include async loading
adrien2p/medusa-extender pull request #149
Opened 2022-12-12 05:48 UTC by SGFGOV

Continuation of feat: added async loading support to medusa #139
fixed merging issues

2022-12-13 17:01 UTC, adrien2p requested changes
LGTM, some linting issues with the fixtures files and one minor comment otherwise it will be good to go 🎉 thanks for you great effort

2022-12-16 08:16 UTC, SGFGOV commented on integration-tests/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
done

2022-12-19 13:36 UTC, merged

2022-12-20 07:15 UTC, SGFGOV commented
@adrien2p , thanks a ton for merging this and being extremely patient with me, please ignore the revert request. accidental click

2022-12-21 07:51 UTC, adrien2p commented
@SGFGOV it is a pleasure. I am planning to release in the near future 💪 thanks for your work 😍